- name: System setup
  hosts: workstation
  become: true
  roles:
    - role: repositories
    - role: nvidia
      tags: nvidia
    - role: common
      tags: common
    - role: gaming
      tags: gaming
    - role: sway
      tags: sway
    - role: jetbrains
      tags: jetbrains