- name: Add Unity Hub repository
  yum_repository:
    name: unityhub
    description: Unity Hub repository
    baseurl: https://hub.unity3d.com/linux/repos/rpm/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://hub.unity3d.com/linux/repos/rpm/stable/repodata/repomd.xml.key

- name: Install Unity Hub
  dnf:
    name: unityhub
    state: present

    